
# WorkFlow Name
name: My First CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  
jobs:
  say-hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello World
        run: echo "Build and Test completed successfully!"